services:
  postgres:
    container_name: fpl_postgres
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

#  fpl:
#    image: macchiato23/free-proxy-list:0.0.1-dev4
#    container_name: free-proxy-list
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - postgres
#    depends_on:
#      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: